# Generated by Django 5.1.2 on 2024-12-08 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='course',
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='year_of_study',
        ),
    ]
